name: Load test
on: [workflow_dispatch]
permissions:
  contents: read
env:
  # For AZURE_WEBAPP_NAME enter just the name, not the full URL.
  RESOURCE_GROUP: az2006-rg
  LOAD_TEST_RESOURCE: az2006loadtest
  AZURE_WEBAPP_NAME: az2006app18114
jobs:
  # This workflow consists of a single job called "loadtest"
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #Login in your azure subscription using client secret credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      # Run the load test
      - name: Azure Load Testing
        uses: azure/load-testing@v1.1.27
        with:
          loadTestConfigFile: 'config.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE}}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          env: |
            [{
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
            }]
      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: ${{github.workspace}}/loadTest
